package nhn.cistory.vo;
/**
 * Table name : obquestion
 * Generated by CUBRID Tools.
 */
public class Obquestion extends Question{
	private Integer ob_num = null;
	private String ob_desc = null;
	private String cho1 = null;
	private String cho2 = null;
	private String cho3 = null;
	private String cho4 = null;
	private String cho5 = null;
	private String ob_sol = null;
	
	public Obquestion(){
		
	}
	
	public Obquestion(Integer ob_num, String ob_desc,
			String cho1, String cho2, String cho3, String cho4, String cho5,
			String ob_sol) {
		super();
		this.ob_num = ob_num;
		this.ob_desc = ob_desc;
		this.cho1 = cho1;
		this.cho2 = cho2;
		this.cho3 = cho3;
		this.cho4 = cho4;
		this.cho5 = cho5;
		this.ob_sol = ob_sol;
	}
	
	public Obquestion(Integer q_num, String question, String q_type,
			String grade, String age, Integer wrongCount, Integer setCount,
			Integer point, String q_exp) {
		super(q_num, question, q_type, grade, age, wrongCount, setCount, point, q_exp);
		// TODO Auto-generated constructor stub
	}
	
	public Integer getOb_num() {
		return ob_num;
	}

	public void setOb_num(Integer ob_num) {
		this.ob_num = ob_num;
	}

	public String getOb_desc() {
		return ob_desc;
	}

	public void setOb_desc(String ob_desc) {
		this.ob_desc = ob_desc;
	}

	public String getCho1() {
		return cho1;
	}

	public void setCho1(String cho1) {
		this.cho1 = cho1;
	}

	public String getCho2() {
		return cho2;
	}

	public void setCho2(String cho2) {
		this.cho2 = cho2;
	}

	public String getCho3() {
		return cho3;
	}

	public void setCho3(String cho3) {
		this.cho3 = cho3;
	}

	public String getCho4() {
		return cho4;
	}

	public void setCho4(String cho4) {
		this.cho4 = cho4;
	}

	public String getCho5() {
		return cho5;
	}

	public void setCho5(String cho5) {
		this.cho5 = cho5;
	}

	public String getOb_sol() {
		return ob_sol;
	}

	public void setOb_sol(String ob_sol) {
		this.ob_sol = ob_sol;
	}

	@Override
	public String toString() {
		return "Obquestion [ob_num=" + ob_num + ", ob_desc=" + ob_desc
				+ ", cho1=" + cho1 + ", cho2=" + cho2 + ", cho3=" + cho3
				+ ", cho4=" + cho4 + ", cho5=" + cho5 + ", ob_sol=" + ob_sol
				+ ", Question()=" + super.toString() + "]";
	}
}
